apiVersion: v1

name: cert-manager-csi-driver-spiffe
type: application
description: A Helm chart for cert-manager-csi-driver-spiffe

home: https://github.com/cert-manager/csi-driver-spiffe
maintainers:
- name: joshvanl
  email: joshua.vanleeuwen@jetstack.io
  url: https://cert-manager.io
sources:
- https://github.com/cert-manager/csi-driver-spiffe

appVersion: v0.2.0
version: v0.2.1
